email/1.0.0/api.yaml
email/1.0.0/requirements.txt
email/1.0.0/src/app.py

Added JSON serialization, added possibility to export just some fields

Update email app

---

owa/1.0.0/Dockerfile
owa/1.0.0/api.yaml
owa/1.0.0/requirements.txt
owa/1.0.0/src/app.py

Application to work with Exchange server via OWA.
Application status:
* Similar to email app approach but in this case this keeps mail structure in json avoiding dotted keys [related issue](https://github.com/frikky/Shuffle/issues/193).
The first docker build will take some time because it needs to compile lxml lib .

Exchange app

---

tools/1.0.0/api.yaml
tools/1.0.0/src/app.py

Created test extract_archive function in tools.
At the moment is not working, the file created on shuffle-files is correct but when I dump the content of filedata['data'] to temporary file the generated file is not a valid zip. 
Probably due to encoding issues, I had to use "ISO-8859-1" in my local test.

WIP: Add compress/extract function to tools

---

misp/1.0.0/api.yaml
misp/1.0.0/src/app.py

Improved search, divided by search attributes, search events and events index.
Added edit index functionality.

Update Misp app

---

tools/1.0.0/api.yaml
tools/1.0.0/requirements.txt
tools/1.0.0/src/app.py

Extract archive was not uploading extracted file on shuffle :P
Added rar/7zip support for extract archive

update on extract

---

owa/1.0.0/api.yaml
owa/1.0.0/src/app.py

Add support for uploading attachment to shuffle after get_mails and add attachments in send_mail

Add attachments support to owa

---

thehive/1.0.0/src/app.py

Fixed: If tag is single is ignored
Sorry for black reformatting :angel:

[Thehive] single task is not added

---

owa/1.0.0/src/app.py
tools/1.0.0/api.yaml
tools/1.0.0/src/app.py

[TOOL]
- extract_archive: added a check if extraction fails (eg on non archive file)
- extract_archive: added support for multiple files
- extract/inflate: changed uid to id to keep standard with other apps 
- filter_list: add nested dict key as field
- filter_list: add is_empty/is_not_empty filtering function
- parse_file_ioc: added function, there is a note because not able to get list of list of ids as input
[OWA]
- need to filter to FileAttachment because in attachments there are also calendar and other items that doesn't have content

Some update on tool / extract

---

tools/1.0.0/src/app.py

An example workflow:
https://gist.github.com/dadokkio/e55fe5d818a4b5e3372aa949476d69b7
The initial check in extract:
`items = file_ids if type(file_ids) == list else file_ids.split(",")`
is to check if the archive is a single uid (eg. like example) or is a list of items to extract (eg. list of zip attachment in email)
Not sure if is the proper way to check but it works :angel:

refactor archive with set_file, get_file functions

---

.github/workflows/ciyaml.yaml
nlp/1.0.0/Dockerfile
nlp/1.0.0/api.yaml
nlp/1.0.0/requirements.txt
nlp/1.0.0/src/app.py
testing/1.0.0/src/app.py

This PR implements:
1 - Updates to CI pipeline. A python script forms the build matrix from the local directory data. PRs to master can be built and tagged easier manual testing. 
2 - Content extraction, including OCR with tika in the NLP app. Future work will need to be added so that it handles file inputs properly.
See example branch tag, which does not override :latest (master) https://hub.docker.com/repository/docker/poopiebear/servicenow
See example builds from PR https://github.com/pooki3bear/Shuffle-apps/actions/runs/410355518
and Master commit https://github.com/pooki3bear/Shuffle-apps/actions/runs/410374876

CI Updates and Content Extraction

---

gpg/1.0.0/api.yaml
misp/1.0.0/api.yaml
misp/1.0.0/src/app.py
owa/1.0.0/src/app.py
tools/1.0.0/api.yaml
tools/1.0.0/src/app.py

[gpg] mispelled pgp
[owa] Add generic exception for login failure
[tools] Removed unused libs
[tools > parse_ioc] Add possibilities to provide multiple ioc types
[tools > extract_archive] Manage nested list, return success true/false and archive filename
[tools > parse_file_ioc] Add support for nested [of nested] lists
[tools > filter_list] Add "starts with", "ends with", "filter files by filetype"
[misp] add download sample by md5 functionality

Minor fixing in multiple apps

---

thehive/1.0.0/api.yaml
thehive/1.0.0/src/app.py

Thehive App enhancement.
- Add query search function.
- Replace String with ContainsString. String is deprecated and won't be ported to TheHive 4. 
ref: https://github.com/TheHive-Project/TheHive4py/blob/1.x/thehive4py/query.py

thehive app enhancement

---

thehive/1.0.0/api.yaml
thehive/1.0.0/src/app.py

Add search capability using custom query on both cases and alerts.

custom query search improve

---

azure-sentinel/1.0.0/api.yaml

Leverage options lists for better user experience.
Not implemented for the `status` field as ideally that would be multi-select. I.e. a user could choose 1, all, or any combination of values (New,Active,Closed).

🧹 Make use of options lists for sentinel

---

testing/1.0.0/src/app.py

Typecasing of number on testing app which will help user to not worry about typing int(1) or number(1) as an input, rather user can insert number only as an input value.

Typecasting of number on testing app.

---

azure-sentinel/1.0.0/api.yaml
azure-sentinel/1.0.0/src/app.py

This PR makes the Sentinel app actually raise errors so the pipeline stops when something fatal happens... like authentication fails. It will return the error text from the Azure API which is usually pretty helpful.
This also addresses a lame logic bug where if you provided only a last modified filter, the query filter would be invalid 🤦‍♂️

Sentinel errors

---

thehive/1.0.0/api.yaml
thehive/1.0.0/src/app.py

This adds the ability to create artifacts/observables and attach them to alerts. This only works on TheHive 4.
Obvious next steps are to include delete and update operations, which should be trivial based on this code.

✨ Add function to create TheHive alert artifacts

---

shuffle-tools/1.0.0/api.yaml
shuffle-tools/1.0.0/src/app.py

Regex replacement/substitution

✨ Add regex replace function

---

Microsoft-Teams/1.0.0/api.yaml
Microsoft-Teams/1.0.0/src/app.py

Add the option to specify the options to be listed when using `send_actionable_msg` action.

Teams multi choice

---

owa/1.0.0/api.yaml
owa/1.0.0/src/app.py

Allow filtering by Category and adding a Category via OWA App

---

shuffle-tools/1.0.0/api.yaml
shuffle-tools/1.0.0/src/app.py

Add base64 encode/decode actions to Shuffle Tools.

Add Base64 encode/decode to Shuffle Tools

---

shuffle-tools/1.0.0/api.yaml
shuffle-tools/1.0.0/src/app.py

Merging datetools app features from https://gitlab.com/synack3/shuffle_dev/-/tree/master/apps/date-tools/1.0.1 into shuffle-tools

Merge datetools features into shuffletools

---

thehive/1.1.2/Dockerfile
thehive/1.1.2/api.yaml
thehive/1.1.2/docker-compose.yml
thehive/1.1.2/env.txt
thehive/1.1.2/requirements.txt
thehive/1.1.2/run
thehive/1.1.2/src/app.py

New Actions added:
- Update Case (update thehive case fields and customfields, allows you to insert a case json instead of filling the field)
- Get Organisations (Get list of all Thehive organisations)
- Create Organisation (Create a new organisation in TheHive)
- Create User (Create a new user in TheHive, it creates the user inside the defined auth organisation)

New Version 1.1.2 - TheHive App

---

thehive/1.1.3/api.yaml
thehive/1.1.3/src/app.py

- add_case_artifact:
- changed id by case_id (BUG)
- added dynamic fields (tlp, ioc, sighted, message)

BUG FIX - add_case_artifact

---

thehive/1.1.3/src/app.py

function __connect_thehive was missing the version argument.

Bug FIX - Create Alert Artifact

---

shuffle-tools/1.0.0/api.yaml
shuffle-tools/1.0.0/src/app.py

This PR add a new action to Shuffle Tool app that permits to check if a given IP is contained in at least one on a networks list  defined in CIDR format.
It returns both if is contained and which networks contain the IP.

[shuffle_tool] Add action to match IP in CIDR network

---

thehive/1.1.3/api.yaml
thehive/1.1.3/src/app.py

Added fields:
- pap
- flag
- Customfields
- CustomJson (import new case by filling only the json)
Corrected:
- TLP level
Beautifying the code:
- TLP, PAP, Severity code
- Tags code

TheHive - Create Case updated

---

Breashsense/1.0.0/api.yaml
Breashsense/1.0.0/src/app.py

Updated and added new actions into Breachsense app

Updated and added new actions into Breachsense app

---

http/1.1.0/src/app.py

Bug fix for https://github.com/Shuffle/python-apps/issues/254

Bug fix for http app replacing single quotes

---

email/1.2.0/src/app.py

I hope this will fix the error!!

Fixed list index out of bound error

---

outlook_owa/1.0.0/src/app.py

ItemAttachments will now be added when attachments are saved.

Updated Outlook app 

---

active-directory/1.0.0/requirements.txt
ad-ldap/1.0.0/requirements.txt
crowdstrike-falcon/1.0.0/requirements.txt
rss/1.0.0/requirements.txt
twitter/1.0.0/requirements.txt
unsupported/attack-predictor/1.0.0/requirements.txt
unsupported/office365mgmt/1.0.0/requirements.txt
vulndb/1.0.0/requirements.txt

This PR assumes that these dependencies were excluded from being pinned on purpose and that they should indeed be pinned, so an build can be repeatable.
I think, I got them all.

Pins any current app dependencies

---

velociraptor/1.0.0/README.md
velociraptor/1.0.0/api.yaml
velociraptor/1.0.0/src/app.py

This PR includes:
- Action/function name correction (`check_client_label` -> `get_client_label`)
- App documentation (including `Overview`, `Actions`, and  `Authentication` sections)

Velociraptor App Updates

---

thehive/1.1.3/api.yaml
thehive/1.1.3/src/app.py

Added update_alert action to TheHIVE app

Added update_alert action to TheHIVE app

---

microsoft-identity-and-access/1.0.0/api.yaml
microsoft-identity-and-access/1.0.0/src/app.py

Added new functions to "Microsoft Identity and Access" App:
- Disable User Account
- Update User Job Title
- Update User Department
- Update User Employee Type
- Update User  Leave Date
- Get User Direct Static Group Assignments
- Remove User From Group

Add new functions to microsoft-identity-and-access

---

shuffle-tools/1.2.0/src/app.py

A debug log which should not have been in there. Making it hard to read the actual logs.

removed debug log
